set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(PI_FARTBOX_TARGET_TRIPLET arm-linux-gnueabihf CACHE STRING "Target GNU triplet")

set(CMAKE_C_COMPILER ${PI_FARTBOX_TARGET_TRIPLET}-gcc)
set(CMAKE_CXX_COMPILER ${PI_FARTBOX_TARGET_TRIPLET}-g++)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(PI_FARTBOX_ARMV6_FLAGS "-march=armv6zk -mfpu=vfp -mfloat-abi=hard -marm")

set(CMAKE_C_FLAGS_INIT "${PI_FARTBOX_ARMV6_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "${PI_FARTBOX_ARMV6_FLAGS}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
